[project]
name = "fleet-intelligence-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "apache-airflow-client>=3.2.1",
    "boto3>=1.43.19",
    "confluent-kafka>=2.14.0",
    "dbt-core>=1.8.8",
    "dbt-snowflake>=1.8.4",
    "fastapi>=0.136.3",
    "great-expectations>=1.17.2",
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "kafka-python>=2.3.1",
    "loguru>=0.7.3",
    "minio>=7.2.20",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "numpy>=2.4.6",
    "openmetadata-ingestion>=1.5.15.2",
    "pandas>=3.0.3",
    "passlib[bcrypt]>=1.7.4",
    "plotly>=6.7.0",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.34.2",
    "snowflake-connector-python>=3.18.0",
    "snowflake-sqlalchemy>=1.10.0",
    "sqlalchemy>=1.4.54",
    "streamlit>=1.58.0",
    "tenacity>=9.1.4",
    "uvicorn[standard]>=0.48.0",
]
